### ISSUE TITLE
Reporte de practica 2 - Validad de documento y proyecto

### ISSUE THREAD

**Issue by irving1989** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-nuggets-de-pollo#2]
[Practica 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-nuggets-de-pollo/files/14314244/Practica.1.pdf)

**Comment by josealfredo79** [comment]
Cual es la calificación..????

**Comment by Alvaro2-0** [comment]
Portada: 25
Procedimiento: 25
Figuras, ilustraciones y fotografías: 25
Resultados y conclusiones: 25
20/20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
